[package]
name = "ommegaclient-b"
authors = ["jiyin004"]
version = "1.3.2"
edition = "2021"
license = "AGPL-3.0-or-later"

[lib]
name = "ommegaclient_b"
path = "src/lib.rs"

[[bin]]
name = "relay"
path = "src/bin/relay.rs"

[dependencies]
kmr-derive = { path = "derive" }
kmr-common = { path = "common" }
kmr-wire = { path = "wire" }
log4rs = "1.4.0"
log = "0.4.33"
rsbinder = { version = "0.10.0", features = ["android_12_plus", "rpc"] }
anyhow = "1.0.104"
async-trait = "0.1.91"
serde_json = "1.0.151"
x509-cert = "0.3.0"
der = "0.8.1"
base64 = "0.23.0"
android_logger = "0.15.1"
multi_log = "0.1.2"
rustls = "0.23"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "blocking"] }

[profile.dev]
incremental = true

[profile.release]
opt-level = 3
lto = true          # Enable link-time optimization
codegen-units = 1   # Reduce number of codegen units to increase optimizations
panic = 'abort'     # Abort on panic
strip = true        # Strip symbols from binary*
debug = 0           # Disable debug info
incremental = true

[workspace]
members = [
  "common",
  "derive",
  "wire",
]

[patch.crates-io]
kmr-derive = { path = "derive" }
kmr-common = { path = "common" }
kmr-wire = { path = "wire" }

[build-dependencies]
prost-build = "0.14.4"
rsbinder-aidl = "0.10.0"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = ["user-hooks"] }
ciborium = "0.2.2"
rcgen = "0.14.8"
tempfile = "3.25.0"
